// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Sample2 {
	
	
	public partial class Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.HtmlControls.HtmlInputText tb1;
		
		protected System.Web.UI.WebControls.Button button1;
		
		protected System.Web.UI.WebControls.Label ErrorString;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Item1;
		
		protected System.Web.UI.HtmlControls.HtmlImage Image;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Firstitem;
		
		protected System.Web.UI.WebControls.Label Name;
		
		protected System.Web.UI.WebControls.Label Date_Released;
		
		protected System.Web.UI.WebControls.Label Rating;
		
		protected System.Web.UI.WebControls.Label Runtime;
		
		protected System.Web.UI.WebControls.Label Genre;
		
		protected System.Web.UI.WebControls.Label Summary;
		
		protected System.Web.UI.WebControls.Label CRating;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Meter;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Item2;
		
		protected System.Web.UI.HtmlControls.HtmlImage Image2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Firstitem2;
		
		protected System.Web.UI.WebControls.Label Shown2;
		
		protected System.Web.UI.WebControls.Label Name2;
		
		protected System.Web.UI.WebControls.Label Date_Released2;
		
		protected System.Web.UI.WebControls.Label Rating2;
		
		protected System.Web.UI.WebControls.Label Runtime2;
		
		protected System.Web.UI.WebControls.Label Genre2;
		
		protected System.Web.UI.WebControls.Label Summary2;
		
		protected System.Web.UI.WebControls.Label CRating2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Meter2;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Item3;
		
		protected System.Web.UI.HtmlControls.HtmlImage Image3;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Firstitem3;
		
		protected System.Web.UI.WebControls.Label Shown3;
		
		protected System.Web.UI.WebControls.Label Name3;
		
		protected System.Web.UI.WebControls.Label Date_Released3;
		
		protected System.Web.UI.WebControls.Label Rating3;
		
		protected System.Web.UI.WebControls.Label Runtime3;
		
		protected System.Web.UI.WebControls.Label Genre3;
		
		protected System.Web.UI.WebControls.Label Summary3;
		
		protected System.Web.UI.WebControls.Label CRating3;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Meter3;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Item4;
		
		protected System.Web.UI.HtmlControls.HtmlImage Image4;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Firstitem4;
		
		protected System.Web.UI.WebControls.Label Shown4;
		
		protected System.Web.UI.WebControls.Label Name4;
		
		protected System.Web.UI.WebControls.Label Date_Released4;
		
		protected System.Web.UI.WebControls.Label Rating4;
		
		protected System.Web.UI.WebControls.Label Runtime4;
		
		protected System.Web.UI.WebControls.Label Genre4;
		
		protected System.Web.UI.WebControls.Label Summary4;
		
		protected System.Web.UI.WebControls.Label CRating4;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Meter4;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Item5;
		
		protected System.Web.UI.HtmlControls.HtmlImage Image5;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Firstitem5;
		
		protected System.Web.UI.WebControls.Label Shown5;
		
		protected System.Web.UI.WebControls.Label Name5;
		
		protected System.Web.UI.WebControls.Label Date_Released5;
		
		protected System.Web.UI.WebControls.Label Rating5;
		
		protected System.Web.UI.WebControls.Label Runtime5;
		
		protected System.Web.UI.WebControls.Label Genre5;
		
		protected System.Web.UI.WebControls.Label Summary5;
		
		protected System.Web.UI.WebControls.Label CRating5;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Meter5;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Item6;
		
		protected System.Web.UI.HtmlControls.HtmlImage Image6;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Firstitem6;
		
		protected System.Web.UI.WebControls.Label Shown6;
		
		protected System.Web.UI.WebControls.Label Name6;
		
		protected System.Web.UI.WebControls.Label Date_Released6;
		
		protected System.Web.UI.WebControls.Label Rating6;
		
		protected System.Web.UI.WebControls.Label Runtime6;
		
		protected System.Web.UI.WebControls.Label Genre6;
		
		protected System.Web.UI.WebControls.Label Summary6;
		
		protected System.Web.UI.WebControls.Label CRating6;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Meter6;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Item7;
		
		protected System.Web.UI.HtmlControls.HtmlImage Image7;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Firstitem7;
		
		protected System.Web.UI.WebControls.Label Shown7;
		
		protected System.Web.UI.WebControls.Label Name7;
		
		protected System.Web.UI.WebControls.Label Date_Released7;
		
		protected System.Web.UI.WebControls.Label Rating7;
		
		protected System.Web.UI.WebControls.Label Runtime7;
		
		protected System.Web.UI.WebControls.Label Genre7;
		
		protected System.Web.UI.WebControls.Label Summary7;
		
		protected System.Web.UI.WebControls.Label CRating7;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Meter7;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Item8;
		
		protected System.Web.UI.HtmlControls.HtmlImage Image8;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Firstitem8;
		
		protected System.Web.UI.WebControls.Label Shown8;
		
		protected System.Web.UI.WebControls.Label Name8;
		
		protected System.Web.UI.WebControls.Label Date_Released8;
		
		protected System.Web.UI.WebControls.Label Rating8;
		
		protected System.Web.UI.WebControls.Label Runtime8;
		
		protected System.Web.UI.WebControls.Label Genre8;
		
		protected System.Web.UI.WebControls.Label Summary8;
		
		protected System.Web.UI.WebControls.Label CRating8;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl Meter8;
	}
}
